Fix C/I, take VIII.i

diff --git a/.github/workflows/windows.yml b/.github/workflows/windows.yml
--- a/.github/workflows/windows.yml
+++ b/.github/workflows/windows.yml
@@ -38,10 +38,10 @@ jobs:
             shell: bash -l {0}
 
         env:
-          source_directory: $GITHUB_WORKSPACE
-          build_directory: $GITHUB_WORKSPACE/../build
-          runtime_install_directory: $GITHUB_WORKSPACE/../runtime_install
-          development_install_directory: $GITHUB_WORKSPACE/../development_install
+          lue_source_directory: $GITHUB_WORKSPACE
+          lue_build_directory: $GITHUB_WORKSPACE/../build
+          lue_runtime_install_directory: $GITHUB_WORKSPACE/../runtime_install
+          lue_development_install_directory: $GITHUB_WORKSPACE/../development_install
           lue_consume_source_directory: $GITHUB_WORKSPACE/../lue_consume
           lue_consume_build_directory: $GITHUB_WORKSPACE/../lue_consume_build
           hpx_version: 1.9.1
@@ -135,16 +135,16 @@ jobs:
               # TODO Use the GDAL Conan package instead of the Conda package, once the GDAL
               #      Conan package actually works
               #      boost gdal hdf5 hwloc mimalloc
-              mkdir ${{ env.build_directory }}
+              mkdir ${{ env.lue_build_directory }}
               LUE_CONAN_PACKAGES="docopt.cpp fmt glfw imgui nlohmann_json vulkan-headers vulkan-loader" \
                   conan install . \
                       --profile:host=host_profile \
                       --profile:build=build_profile \
                       --build=missing \
-                      --output-folder=${{ env.build_directory }}
-              CMAKE_PREFIX_PATH=${{ env.build_directory }} \
+                      --output-folder=${{ env.lue_build_directory }}
+              CMAKE_PREFIX_PATH=${{ env.lue_build_directory }} \
                   cmake --preset conan-release \
-                      -B ${{ env.build_directory }} \
+                      -B ${{ env.lue_build_directory }} \
                       -D LUE_BUILD_QA=TRUE \
                       -D LUE_QA_WITH_PYTHON_API=TRUE \
                       -D LUE_QA_WITH_TESTS=TRUE \
@@ -158,42 +158,42 @@ jobs:
 
         - name: build
           run: |
-              cmake --build ${{ env.build_directory }} --target all
+              cmake --build ${{ env.lue_build_directory }} --target all
 
         - name: install
           run: |
               cmake \
-                  --install ${{ env.build_directory }} \
-                  --prefix ${{ env.runtime_install_directory }} \
+                  --install ${{ env.lue_build_directory }} \
+                  --prefix ${{ env.lue_runtime_install_directory }} \
                   --component lue_runtime \
                   --strip
               cmake \
-                  --install ${{ env.build_directory }} \
-                  --prefix ${{ env.development_install_directory }} \
+                  --install ${{ env.lue_build_directory }} \
+                  --prefix ${{ env.lue_development_install_directory }} \
                   --component lue_development \
                   --strip
 
         - name: test
           run: |
               # Unit tests
-              ctest --test-dir ${{ env.build_directory }} --output-on-failure
+              ctest --test-dir ${{ env.lue_build_directory }} --output-on-failure
 
               # Tests of runtime targets
               # Add location of dependencies installed with Conan to the runtime environment
-              ${{ env.build_directory }}/conanrun.bat
+              ${{ env.lue_build_directory }}/conanrun.bat
 
-              export PATH="${{ env.runtime_install_directory }}/bin:$PATH"
-              ${{ env.runtime_install_directory }}/bin/lue_translate --version
-              ${{ env.runtime_install_directory }}/bin/lue_validate --version
-              ${{ env.runtime_install_directory }}/bin/lue_view --version || echo "TODO: Error executing lue_view!"
+              export PATH="${{ env.lue_runtime_install_directory }}/bin:$PATH"
+              ${{ env.lue_runtime_install_directory }}/bin/lue_translate --version
+              ${{ env.lue_runtime_install_directory }}/bin/lue_validate --version
+              ${{ env.lue_runtime_install_directory }}/bin/lue_view --version || echo "TODO: Error executing lue_view!"
 
               # Add our package to the set of Conda packages
-              conda-develop ${{ env.runtime_install_directory }}/lib/python${{ matrix.python_version }}
-              ${{ env.runtime_install_directory }}/bin/lue_calculate --version
-              ${{ env.runtime_install_directory }}/bin/lue_scalability --version
+              conda-develop ${{ env.lue_runtime_install_directory }}/lib/python${{ matrix.python_version }}
+              ${{ env.lue_runtime_install_directory }}/bin/lue_calculate --version
+              ${{ env.lue_runtime_install_directory }}/bin/lue_scalability --version
               python -c "import lue, lue.data_model, lue.framework, lue.pcraster, lue.qa.scalability; print(lue.__version__)"
 
-              dumpbin //imports ${{ env.runtime_install_directory }}/bin/lue_view.exe
+              dumpbin //imports ${{ env.lue_runtime_install_directory }}/bin/lue_view.exe
 
               # Test of imported CMake targets
               git clone https://github.com/computationalgeography/lue_consume.git ${{ env.lue_consume_source_directory }}
@@ -204,7 +204,7 @@ jobs:
                   -D CMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }} \
                   -D CMAKE_BUILD_TYPE=Release \
                   -D CMAKE_POLICY_DEFAULT_CMP0144=NEW \
-                  -D LUE_ROOT=${{ env.development_install_directory }} \
+                  -D LUE_ROOT=${{ env.lue_development_install_directory }} \
                   -D HPX_ROOT=${{ env.hpx_install_directory }} \
                   -D MDSPAN_ROOT=${{ env.mdspan_install_directory }}
               cmake --build ${{ env.lue_consume_build_directory }} --target all
